BEGIN;

-- ============================================================
-- Roles
-- ============================================================
INSERT INTO roles (name, description, is_system) VALUES
    ('platform_admin',   'Full platform access — tenant management, billing, licensing, impersonation', TRUE),
    ('platform_support', 'Read access to all tenants, can impersonate, cannot modify billing or licensing', TRUE),
    ('platform_finance', 'Billing & licensing management, no impersonation or tenant data access', TRUE),
    ('firm_admin',       'Full control of firm + all managed HOAs', TRUE),
    ('firm_staff',       'Operational staff — day-to-day management across assigned HOAs', TRUE),
    ('firm_support',     'Support staff — handles maintenance requests, homeowner comms, limited admin', TRUE),
    ('hoa_manager',      'Operational management of a single HOA', TRUE),
    ('vendor_contact',   'External vendor rep — work orders, invoices, job status', TRUE),
    ('board_president',  'Full HOA governance authority + operational oversight', TRUE),
    ('board_member',     'Board-level governance access', TRUE),
    ('homeowner',        'Own unit, payments, requests', TRUE);

-- ============================================================
-- Permissions
-- ============================================================
INSERT INTO permissions (key, description, module) VALUES
    -- org
    ('org.organization.create',      'Create organizations',              'org'),
    ('org.organization.read',        'Read organizations',                'org'),
    ('org.organization.update',      'Update organizations',              'org'),
    ('org.organization.delete',      'Delete organizations',              'org'),
    ('org.membership.manage',        'Manage memberships',                'org'),
    ('org.membership.read',          'Read memberships',                  'org'),
    ('org.unit.create',              'Create units',                      'org'),
    ('org.unit.read',                'Read units',                        'org'),
    ('org.unit.update',              'Update units',                      'org'),
    ('org.vendor.manage',            'Manage vendors',                    'org'),
    ('org.vendor.read',              'Read vendors',                      'org'),
    ('org.unit_membership.manage',   'Manage unit memberships',           'org'),
    ('org.unit_membership.read',     'Read unit memberships',             'org'),
    ('org.transfer.manage',          'Manage transfers',                  'org'),
    ('org.transfer.read',            'Read transfers',                    'org'),
    ('org.amenity.manage',           'Manage amenities',                  'org'),
    ('org.amenity.read',             'Read amenities',                    'org'),
    ('org.reservation.create',       'Create reservations',               'org'),
    ('org.reservation.read',         'Read reservations',                 'org'),
    ('org.reservation.manage',       'Manage reservations',               'org'),
    ('org.registration_type.manage', 'Manage registration types',         'org'),
    ('org.registration.create',      'Create registrations',              'org'),
    ('org.registration.read',        'Read registrations',                'org'),
    ('org.registration.manage',      'Manage registrations',              'org'),
    -- fin
    ('fin.schedule.manage',          'Manage fee schedules',              'fin'),
    ('fin.schedule.read',            'Read fee schedules',                'fin'),
    ('fin.assessment.create',        'Create assessments',                'fin'),
    ('fin.assessment.read',          'Read assessments',                  'fin'),
    ('fin.assessment.update',        'Update assessments',                'fin'),
    ('fin.ledger.read',              'Read ledger',                       'fin'),
    ('fin.payment.create',           'Create payments',                   'fin'),
    ('fin.payment.read',             'Read payments',                     'fin'),
    ('fin.payment_method.manage',    'Manage payment methods',            'fin'),
    ('fin.budget.create',            'Create budgets',                    'fin'),
    ('fin.budget.read',              'Read budgets',                      'fin'),
    ('fin.budget.approve',           'Approve budgets',                   'fin'),
    ('fin.expense.submit',           'Submit expenses',                   'fin'),
    ('fin.expense.read',             'Read expenses',                     'fin'),
    ('fin.expense.approve',          'Approve expenses',                  'fin'),
    ('fin.fund.manage',              'Manage funds',                      'fin'),
    ('fin.fund.read',                'Read funds',                        'fin'),
    ('fin.fund.transfer',            'Transfer between funds',            'fin'),
    ('fin.collection.read',          'Read collections',                  'fin'),
    ('fin.collection.manage',        'Manage collections',                'fin'),
    ('fin.payment_plan.manage',      'Manage payment plans',              'fin'),
    -- gov
    ('gov.violation.create',         'Create violations',                 'gov'),
    ('gov.violation.read',           'Read violations',                   'gov'),
    ('gov.violation.manage',         'Manage violations',                 'gov'),
    ('gov.hearing.manage',           'Manage hearings',                   'gov'),
    ('gov.arb.submit',               'Submit arbitration requests',       'gov'),
    ('gov.arb.read',                 'Read arbitration',                  'gov'),
    ('gov.arb.review',               'Review arbitration',                'gov'),
    ('gov.ballot.create',            'Create ballots',                    'gov'),
    ('gov.ballot.read',              'Read ballots',                      'gov'),
    ('gov.ballot.vote',              'Vote on ballots',                   'gov'),
    ('gov.proxy.file',               'File proxy votes',                  'gov'),
    ('gov.proxy.read',               'Read proxy votes',                  'gov'),
    ('gov.meeting.create',           'Create meetings',                   'gov'),
    ('gov.meeting.read',             'Read meetings',                     'gov'),
    ('gov.meeting.manage',           'Manage meetings',                   'gov'),
    ('gov.motion.create',            'Create motions',                    'gov'),
    ('gov.motion.read',              'Read motions',                      'gov'),
    -- com
    ('com.announcement.create',      'Create announcements',              'com'),
    ('com.announcement.read',        'Read announcements',                'com'),
    ('com.thread.create',            'Create threads',                    'com'),
    ('com.thread.read',              'Read threads',                      'com'),
    ('com.message.send',             'Send messages',                     'com'),
    ('com.calendar_event.create',    'Create calendar events',            'com'),
    ('com.calendar_event.read',      'Read calendar events',              'com'),
    ('com.calendar_event.manage',    'Manage calendar events',            'com'),
    ('com.calendar.read',            'Read calendar',                     'com'),
    ('com.template.manage',          'Manage communication templates',    'com'),
    ('com.directory.read',           'Read directory',                    'com'),
    ('com.comm_log.create',          'Create communication log entries',  'com'),
    ('com.comm_log.read',            'Read own communication log',        'com'),
    ('com.comm_log.read_all',        'Read all communication logs',       'com'),
    -- doc
    ('doc.document.upload',          'Upload documents',                  'doc'),
    ('doc.document.read',            'Read documents',                    'doc'),
    ('doc.document.manage',          'Manage documents',                  'doc'),
    ('doc.version.create',           'Create document versions',          'doc'),
    ('doc.compliance.read',          'Read compliance documents',         'doc'),
    -- task
    ('task.create',                  'Create tasks',                      'task'),
    ('task.read',                    'Read tasks',                        'task'),
    ('task.manage',                  'Manage tasks',                      'task'),
    ('task.assign',                  'Assign tasks',                      'task'),
    ('task.transition',              'Transition task status',            'task'),
    ('task.comment',                 'Comment on tasks',                  'task'),
    ('task.type.manage',             'Manage task types',                 'task'),
    ('task.dashboard',               'Access task dashboard',             'task'),
    -- audit
    ('audit.log.read',               'Read audit logs',                   'audit'),
    -- admin
    ('admin.tenant.manage',          'Manage tenants',                    'admin'),
    ('admin.tenant.read',            'Read tenants',                      'admin'),
    ('admin.impersonate',            'Impersonate users',                 'admin'),
    ('admin.feature_flag.manage',    'Manage feature flags',              'admin'),
    -- license
    ('license.plan.manage',          'Manage license plans',              'license'),
    ('license.subscription.read',    'Read subscriptions',                'license'),
    ('license.subscription.manage',  'Manage subscriptions',              'license'),
    ('license.usage.read',           'Read license usage',                'license'),
    -- billing
    ('billing.account.manage',       'Manage billing accounts',           'billing'),
    ('billing.invoice.read',         'Read invoices',                     'billing'),
    -- ai
    ('ai.governing_doc.manage',      'Manage governing documents (AI)',   'ai'),
    ('ai.governing_doc.read',        'Read governing documents (AI)',     'ai'),
    ('ai.extraction.review',         'Review AI extractions',             'ai'),
    ('ai.extraction.read',           'Read AI extractions',               'ai'),
    ('ai.policy.read',               'Read AI policies',                  'ai'),
    ('ai.policy.query',              'Query AI policies',                 'ai'),
    ('ai.resolution.decide',         'Decide AI resolutions',             'ai'),
    ('ai.resolution.read',           'Read AI resolutions',               'ai'),
    ('ai.config.manage',             'Manage AI configuration',           'ai'),
    -- webhook
    ('webhook.manage',               'Manage webhooks',                   'webhook'),
    ('webhook.read',                 'Read webhooks',                     'webhook');

-- ============================================================
-- Role → Permission mappings
-- ============================================================

-- platform_admin: ALL permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'platform_admin';

-- platform_support
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'platform_support'
AND p.key IN (
    'org.organization.read',
    'org.membership.read',
    'org.unit.read',
    'org.unit_membership.read',
    'org.transfer.read',
    'org.amenity.read',
    'org.reservation.read',
    'org.registration.read',
    'fin.schedule.read',
    'fin.assessment.read',
    'fin.ledger.read',
    'fin.payment.read',
    'fin.budget.read',
    'fin.expense.read',
    'fin.fund.read',
    'fin.collection.read',
    'gov.violation.read',
    'gov.arb.read',
    'gov.ballot.read',
    'gov.meeting.read',
    'gov.motion.read',
    'com.announcement.read',
    'com.thread.read',
    'com.calendar_event.read',
    'com.calendar.read',
    'com.directory.read',
    'com.comm_log.read',
    'doc.document.read',
    'task.read',
    'task.dashboard',
    'audit.log.read',
    'admin.tenant.read',
    'admin.impersonate',
    'license.subscription.read',
    'license.usage.read',
    'billing.invoice.read',
    'ai.governing_doc.read',
    'ai.extraction.read',
    'ai.policy.read',
    'ai.resolution.read',
    'webhook.read'
);

-- platform_finance
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'platform_finance'
AND p.key IN (
    'license.plan.manage',
    'license.subscription.read',
    'license.subscription.manage',
    'license.usage.read',
    'billing.account.manage',
    'billing.invoice.read'
);

-- firm_admin
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'firm_admin'
AND p.key IN (
    'org.organization.create',
    'org.organization.read',
    'org.organization.update',
    'org.membership.manage',
    'org.membership.read',
    'org.unit.create',
    'org.unit.read',
    'org.unit.update',
    'org.vendor.manage',
    'org.vendor.read',
    'org.unit_membership.manage',
    'org.unit_membership.read',
    'org.transfer.manage',
    'org.transfer.read',
    'org.amenity.manage',
    'org.amenity.read',
    'org.reservation.create',
    'org.reservation.read',
    'org.reservation.manage',
    'org.registration_type.manage',
    'org.registration.create',
    'org.registration.read',
    'org.registration.manage',
    'fin.schedule.manage',
    'fin.schedule.read',
    'fin.assessment.create',
    'fin.assessment.read',
    'fin.assessment.update',
    'fin.ledger.read',
    'fin.payment.create',
    'fin.payment.read',
    'fin.budget.create',
    'fin.budget.read',
    'fin.budget.approve',
    'fin.expense.submit',
    'fin.expense.read',
    'fin.expense.approve',
    'fin.fund.manage',
    'fin.fund.read',
    'fin.fund.transfer',
    'fin.collection.read',
    'fin.collection.manage',
    'fin.payment_plan.manage',
    'gov.violation.create',
    'gov.violation.read',
    'gov.violation.manage',
    'gov.hearing.manage',
    'gov.arb.read',
    'gov.arb.review',
    'gov.ballot.create',
    'gov.ballot.read',
    'gov.proxy.read',
    'gov.meeting.create',
    'gov.meeting.read',
    'gov.meeting.manage',
    'gov.motion.read',
    'com.announcement.create',
    'com.announcement.read',
    'com.thread.create',
    'com.thread.read',
    'com.message.send',
    'com.calendar_event.create',
    'com.calendar_event.read',
    'com.calendar_event.manage',
    'com.calendar.read',
    'com.template.manage',
    'com.directory.read',
    'com.comm_log.create',
    'com.comm_log.read',
    'com.comm_log.read_all',
    'doc.document.upload',
    'doc.document.read',
    'doc.document.manage',
    'doc.version.create',
    'doc.compliance.read',
    'task.create',
    'task.read',
    'task.manage',
    'task.assign',
    'task.transition',
    'task.comment',
    'task.type.manage',
    'task.dashboard',
    'audit.log.read',
    'license.subscription.read',
    'license.subscription.manage',
    'license.usage.read',
    'billing.account.manage',
    'billing.invoice.read',
    'ai.governing_doc.manage',
    'ai.governing_doc.read',
    'ai.extraction.review',
    'ai.extraction.read',
    'ai.policy.read',
    'ai.policy.query',
    'ai.resolution.decide',
    'ai.resolution.read',
    'ai.config.manage',
    'webhook.manage',
    'webhook.read'
);

-- firm_staff
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'firm_staff'
AND p.key IN (
    'org.organization.read',
    'org.membership.read',
    'org.unit.create',
    'org.unit.read',
    'org.unit.update',
    'org.vendor.manage',
    'org.vendor.read',
    'org.unit_membership.manage',
    'org.unit_membership.read',
    'org.transfer.manage',
    'org.transfer.read',
    'org.amenity.manage',
    'org.amenity.read',
    'org.reservation.create',
    'org.reservation.read',
    'org.registration.create',
    'org.registration.read',
    'org.registration.manage',
    'fin.schedule.manage',
    'fin.schedule.read',
    'fin.assessment.create',
    'fin.assessment.read',
    'fin.assessment.update',
    'fin.ledger.read',
    'fin.payment.read',
    'fin.budget.read',
    'fin.expense.submit',
    'fin.expense.read',
    'fin.fund.read',
    'fin.collection.read',
    'fin.collection.manage',
    'fin.payment_plan.manage',
    'gov.violation.create',
    'gov.violation.read',
    'gov.violation.manage',
    'gov.arb.read',
    'gov.ballot.read',
    'gov.meeting.read',
    'gov.motion.read',
    'com.announcement.create',
    'com.announcement.read',
    'com.thread.create',
    'com.thread.read',
    'com.message.send',
    'com.calendar_event.create',
    'com.calendar_event.read',
    'com.calendar_event.manage',
    'com.calendar.read',
    'com.directory.read',
    'com.comm_log.create',
    'com.comm_log.read',
    'com.comm_log.read_all',
    'doc.document.upload',
    'doc.document.read',
    'doc.version.create',
    'doc.compliance.read',
    'task.create',
    'task.read',
    'task.manage',
    'task.assign',
    'task.transition',
    'task.comment',
    'task.dashboard',
    'ai.governing_doc.read',
    'ai.extraction.read',
    'ai.policy.read',
    'ai.policy.query',
    'ai.resolution.read',
    'webhook.read'
);

-- firm_support
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'firm_support'
AND p.key IN (
    'org.organization.read',
    'org.membership.read',
    'org.unit.read',
    'org.vendor.read',
    'org.unit_membership.read',
    'fin.schedule.read',
    'fin.assessment.read',
    'fin.payment.read',
    'fin.budget.read',
    'fin.expense.read',
    'fin.fund.read',
    'gov.violation.create',
    'gov.violation.read',
    'gov.arb.read',
    'gov.ballot.read',
    'gov.meeting.read',
    'gov.motion.read',
    'com.announcement.read',
    'com.thread.create',
    'com.thread.read',
    'com.message.send',
    'com.calendar_event.read',
    'com.calendar.read',
    'com.directory.read',
    'com.comm_log.create',
    'com.comm_log.read',
    'doc.document.read',
    'task.create',
    'task.read',
    'task.transition',
    'task.comment',
    'task.dashboard',
    'ai.policy.read',
    'ai.policy.query'
);

-- hoa_manager: identical to firm_staff
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'hoa_manager'
AND p.key IN (
    'org.organization.read',
    'org.membership.read',
    'org.unit.create',
    'org.unit.read',
    'org.unit.update',
    'org.vendor.manage',
    'org.vendor.read',
    'org.unit_membership.manage',
    'org.unit_membership.read',
    'org.transfer.manage',
    'org.transfer.read',
    'org.amenity.manage',
    'org.amenity.read',
    'org.reservation.create',
    'org.reservation.read',
    'org.registration.create',
    'org.registration.read',
    'org.registration.manage',
    'fin.schedule.manage',
    'fin.schedule.read',
    'fin.assessment.create',
    'fin.assessment.read',
    'fin.assessment.update',
    'fin.ledger.read',
    'fin.payment.read',
    'fin.budget.read',
    'fin.expense.submit',
    'fin.expense.read',
    'fin.fund.read',
    'fin.collection.read',
    'fin.collection.manage',
    'fin.payment_plan.manage',
    'gov.violation.create',
    'gov.violation.read',
    'gov.violation.manage',
    'gov.arb.read',
    'gov.ballot.read',
    'gov.meeting.read',
    'gov.motion.read',
    'com.announcement.create',
    'com.announcement.read',
    'com.thread.create',
    'com.thread.read',
    'com.message.send',
    'com.calendar_event.create',
    'com.calendar_event.read',
    'com.calendar_event.manage',
    'com.calendar.read',
    'com.directory.read',
    'com.comm_log.create',
    'com.comm_log.read',
    'com.comm_log.read_all',
    'doc.document.upload',
    'doc.document.read',
    'doc.version.create',
    'doc.compliance.read',
    'task.create',
    'task.read',
    'task.manage',
    'task.assign',
    'task.transition',
    'task.comment',
    'task.dashboard',
    'ai.governing_doc.read',
    'ai.extraction.read',
    'ai.policy.read',
    'ai.policy.query',
    'ai.resolution.read',
    'webhook.read'
);

-- vendor_contact
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'vendor_contact'
AND p.key IN (
    'org.vendor.read',
    'gov.ballot.read',
    'com.thread.create',
    'com.thread.read',
    'com.message.send',
    'task.read',
    'task.transition',
    'task.comment'
);

-- board_president
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'board_president'
AND p.key IN (
    'org.organization.read',
    'org.organization.update',
    'org.membership.manage',
    'org.membership.read',
    'org.unit.create',
    'org.unit.read',
    'org.unit.update',
    'org.vendor.manage',
    'org.vendor.read',
    'org.unit_membership.manage',
    'org.unit_membership.read',
    'org.transfer.manage',
    'org.transfer.read',
    'org.amenity.manage',
    'org.amenity.read',
    'org.reservation.create',
    'org.reservation.read',
    'org.registration_type.manage',
    'org.registration.create',
    'org.registration.read',
    'org.registration.manage',
    'fin.schedule.manage',
    'fin.schedule.read',
    'fin.assessment.create',
    'fin.assessment.read',
    'fin.assessment.update',
    'fin.ledger.read',
    'fin.payment.create',
    'fin.payment.read',
    'fin.budget.create',
    'fin.budget.read',
    'fin.budget.approve',
    'fin.expense.submit',
    'fin.expense.read',
    'fin.expense.approve',
    'fin.fund.manage',
    'fin.fund.read',
    'fin.fund.transfer',
    'fin.collection.read',
    'fin.collection.manage',
    'fin.payment_plan.manage',
    'gov.violation.create',
    'gov.violation.read',
    'gov.violation.manage',
    'gov.hearing.manage',
    'gov.arb.read',
    'gov.arb.review',
    'gov.ballot.create',
    'gov.ballot.read',
    'gov.proxy.read',
    'gov.meeting.create',
    'gov.meeting.read',
    'gov.meeting.manage',
    'gov.motion.create',
    'gov.motion.read',
    'com.announcement.create',
    'com.announcement.read',
    'com.thread.create',
    'com.thread.read',
    'com.message.send',
    'com.calendar_event.create',
    'com.calendar_event.read',
    'com.calendar_event.manage',
    'com.calendar.read',
    'com.template.manage',
    'com.directory.read',
    'com.comm_log.create',
    'com.comm_log.read',
    'com.comm_log.read_all',
    'doc.document.upload',
    'doc.document.read',
    'doc.document.manage',
    'doc.version.create',
    'doc.compliance.read',
    'task.create',
    'task.read',
    'task.manage',
    'task.assign',
    'task.transition',
    'task.comment',
    'task.type.manage',
    'task.dashboard',
    'audit.log.read',
    'license.subscription.read',
    'license.subscription.manage',
    'billing.account.manage',
    'billing.invoice.read',
    'ai.governing_doc.manage',
    'ai.governing_doc.read',
    'ai.extraction.review',
    'ai.extraction.read',
    'ai.policy.read',
    'ai.policy.query',
    'ai.resolution.decide',
    'ai.resolution.read',
    'ai.config.manage',
    'webhook.manage',
    'webhook.read'
);

-- board_member
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'board_member'
AND p.key IN (
    'org.organization.read',
    'org.membership.read',
    'org.unit.read',
    'org.unit_membership.read',
    'org.transfer.read',
    'org.amenity.read',
    'org.reservation.create',
    'org.reservation.read',
    'org.registration.create',
    'org.registration.read',
    'fin.schedule.read',
    'fin.assessment.read',
    'fin.ledger.read',
    'fin.payment.read',
    'fin.budget.create',
    'fin.budget.read',
    'fin.budget.approve',
    'fin.expense.submit',
    'fin.expense.read',
    'fin.expense.approve',
    'fin.fund.read',
    'fin.collection.read',
    'gov.violation.create',
    'gov.violation.read',
    'gov.violation.manage',
    'gov.arb.read',
    'gov.arb.review',
    'gov.ballot.create',
    'gov.ballot.read',
    'gov.proxy.read',
    'gov.meeting.read',
    'gov.motion.create',
    'gov.motion.read',
    'com.announcement.create',
    'com.announcement.read',
    'com.thread.create',
    'com.thread.read',
    'com.message.send',
    'com.calendar_event.create',
    'com.calendar_event.read',
    'com.calendar.read',
    'com.directory.read',
    'com.comm_log.create',
    'com.comm_log.read',
    'doc.document.upload',
    'doc.document.read',
    'doc.version.create',
    'doc.compliance.read',
    'task.create',
    'task.read',
    'task.transition',
    'task.comment',
    'task.dashboard',
    'audit.log.read',
    'ai.governing_doc.read',
    'ai.extraction.review',
    'ai.extraction.read',
    'ai.policy.read',
    'ai.policy.query',
    'ai.resolution.decide',
    'ai.resolution.read'
);

-- homeowner
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'homeowner'
AND p.key IN (
    'org.organization.read',
    'org.unit.read',
    'org.unit_membership.read',
    'org.transfer.read',
    'org.amenity.read',
    'org.reservation.create',
    'org.reservation.read',
    'org.registration.create',
    'org.registration.read',
    'fin.assessment.read',
    'fin.ledger.read',
    'fin.payment.create',
    'fin.payment.read',
    'fin.payment_method.manage',
    'fin.budget.read',
    'fin.collection.read',
    'gov.violation.read',
    'gov.arb.submit',
    'gov.arb.read',
    'gov.ballot.read',
    'gov.ballot.vote',
    'gov.proxy.file',
    'gov.proxy.read',
    'gov.meeting.read',
    'gov.motion.read',
    'com.announcement.read',
    'com.thread.create',
    'com.thread.read',
    'com.message.send',
    'com.calendar_event.read',
    'com.calendar.read',
    'com.directory.read',
    'com.comm_log.read',
    'doc.document.read',
    'task.read',
    'task.transition',
    'task.comment',
    'audit.log.read',
    'ai.policy.read',
    'ai.policy.query'
);

COMMIT;
